name: Main Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image
        run: docker pull coherentsolutions/rest-training:2.0

      - name: Run Docker container
        run: docker run -d -p 5050:8082 coherentsolutions/rest-training:2.0

      - name: Wait for the container to be ready
        run: sleep 30

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
          
      - name: Restore NuGet packages
        run: dotnet restore RestApiCSharp2.sln

      - name: Build the project
        run: dotnet build RestApiCSharp2.sln --configuration Release

      - name: Run tests
        run: dotnet test RestApiCSharp2.sln --configuration Release 

